image: golang:1.9

stages:
  - test
  - build
  - release

test:
  stage: test
  script:
    - GOPATH=$(mktemp -d)
    - PATH=$GOPATH/bin:$PATH
    - PROJECT=$(basename $CI_PROJECT_DIR)
    - GROUP=$(basename $(dirname $CI_PROJECT_DIR))
    - WORKDIR=$GOPATH/src/gitlab.com/$GROUP/$PROJECT
    - mkdir -p $WORKDIR
    - cp -a * $WORKDIR
    - go get -u github.com/golang/dep/cmd/dep
    - cd $WORKDIR 
    - dep ensure -v
    - make test
  except:
    - master

build:
  stage: build
  script:
    - GOPATH=$(mktemp -d)
    - PATH=$GOPATH/bin:$PATH
    - PROJECT=$(basename $CI_PROJECT_DIR)
    - GROUP=$(basename $(dirname $CI_PROJECT_DIR))
    - WORKDIR=$GOPATH/src/gitlab.com/$GROUP/$PROJECT
    - mkdir -p $WORKDIR
    - cp -a * $WORKDIR
    - go get -u github.com/golang/dep/cmd/dep
    - cd $WORKDIR 
    - dep ensure -v
    - make build
    - cp -r build ${CI_PROJECT_DIR}
  artifacts:
    paths:
      - build/linux/meeseeks-box
      - build/arm/meeseeks-box
      - build/darwin/meeseeks-box
    expire_in: 1 week
  only:
    - master

release:
  stage: release
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    - apk add --no-cache make
    - make release
  only:
    - tags
    - master
