image: golang:1.9

stages:
  - test

before_script:

test:
  stage: test
  script:
    - GOPATH=$(mktemp -d)
    - PATH=${GOPATH}/bin:${PATH}
    - PROJECT=$(basename ${CI_PROJECT_DIR})
    - GROUP=$(basename $(dirname ${CI_PROJECT_DIR}))
    - WORKDIR=${GOPATH}/src/gitlab.com/${GROUP}/${PROJECT}
    - mkdir -p ${WORKDIR}
    - cp -a * ${WORKDIR}
    - go get -u github.com/golang/dep/cmd/dep
    - cd ${WORKDIR} 
    - dep ensure -v
    - make test
