language: go
go:
- 1.9.x

matrix:
  fast_finish: true

before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- go get github.com/golang/lint/golint
- go get honnef.co/go/tools/cmd/megacheck
- go get github.com/fzipp/gocyclo

install:
- go get -u github.com/golang/dep/...
- dep ensure

script:
- test -z $(gofmt -s -l $GO_FILES)
- find . -iname '*.go' -type f -not -path './vendor/*' -exec gofmt -s -l {} \;
- go test -v -race ./...
- go vet ./...
- megacheck $(go list ./...)
- gocyclo -over 19 $GO_FILES
- golint -set_exit_status $(go list ./...)
- go build

notifications:
  slack:
    secure: Pg3oxMvTqwwKola/f6w1X5J1iRilBebn0+ajUgzhSIIpS+u+qUNC11nastZkckEQ2VST51gfzOFeIB9DcU2/tPGHoqBTNREvnWwCzu+ED2Ej5wVDih33vDwlBivMagIxEMHJfdLdAHImsQzZwlpMQZepZwz6ndqlCvsI4BovWgqTbPVShbS0qUIFvnZoTIgZFlfrL6x2lAvKAZVeC4Un0UBCXeL7deDcf+nYiQzMbCy86fKieAbwN4BIEFRc9J2s4YfOWWqeXipgifplL9eRht+vFYOTOAnPDn8Rg/iey4kdoID2cNMzvRwjfxxAKy8Tb/AmS4oAQQ53xP4eybn7b7w+9ZWGnOwY7yMNojKFMVt3ka9fW7+rfb6+Dhi4CgtVOeUI8S9oQ1tJdfkHIzbvuy26pXi3N5IYz9eI25c72DlcGXNnAozx/+NQ9hE07+jOhxVU82tQHXIeRA1anxUk+3uB8afXQ2mI5Zw/IfiuiWznCsaTTiN66KUFFbe197f9ciZ2K3rU2h3qUHzmlVtmfywmRq2aTvuyYblPKGmWq/IV7+Ty/Sx/askVtmxDTG3UqAObPddNG8kmpjYYIUb1wq/pC8NkI+yMY2ehNwF3I/YnnLWM0D/JJqFqXunhCWAm1lEoX3xBQRKu+q/xYRe8XTy0ooJu08DeyelgbSM2k9s=
