---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: meeseeks
  labels:
    app: meeseeks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeseeks
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: meeseeks
      labels:
        app: meeseeks
    spec:
      containers:
      - name: meeseeks
        image: yakshaving.art/meeseeks-box
        env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-token
              key: slack-token
        resources:
          limits:
            memory: "64Mi"
        args:
        - '-config=/etc/meeseeks/meeseeks.yml'
        volumeMounts:
        - name: config-volume
          mountPath: /etc/meeseeks
        - name: meeseeks-db
          mountPath: /var/lib/meeseeks
      volumes:
      - name: config-volume
        configMap:
          name: meeseeks
      - name: meeseeks-db
        emptyDir: {}
